### ISSUE TITLE
Xcode 6.3 support

### ISSUE THREAD

**Issue by clayzhu** [shjborage/Reveal-Plugin-for-Xcode#12]
Apple released Xcode 6.3 yesterday, but I found the Reveal Plugin would not work any more. I wish that this great and convenient plugin can support Xcode 6.3 soon. Thanks.

**Comment by shjborage** [comment]
OK, I will support Xcode 6.3 soon.

**Comment by shjborage** [comment]
93b68ea738a35157fce21fbe0242c1bcf162ca1a done!
