### ISSUE TITLE
真机为何连不上啊？

### ISSUE THREAD

**Issue by tangkunyin** [shjborage/Reveal-Plugin-for-Xcode#13]
用模拟器是没有问题的，但是真机连接不上，总提示“An unexpected error occurred, please try again later!”，确认过真机和电脑出于同意网段，最后在您博客看到这个插件仅适用于模拟器，不知道能不能研究出真机调试的解决方案呢？

**Comment by shjborage** [comment]
您好，真机的话因为不能动态注入lib，所以目前插件不支持。真机的话可以手动添加framework到工程中，按Reveal官方的教程来走。

**Comment by tangkunyin** [comment]
嗯，明白了，多谢大侠！

**Comment by shjborage** [comment]
不客气，有问题再联系我。
