### ISSUE TITLE
XCode 7.1 support

### ISSUE THREAD

**Issue by jalmaas** [shjborage/Reveal-Plugin-for-Xcode#22]
Any plans for updating this to 7.1-support?

**Comment by hfossli** [comment]
Ah, yes, I was wondering why the plugin didn't show in the menu.

**Comment by jalmaas** [comment]
I made a PR adding the 7.1 DVTPlugInCompatibilityUUID. Hope that is enough

**Comment by shjborage** [comment]
done!
